// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0izCiywb0oW9x3F8GrgxDoY7-dFgX69Y',
    appId: '1:1047895517233:web:ee6ae568a5e310c8d90d10',
    messagingSenderId: '1047895517233',
    projectId: 'fireguardpro-ba880',
    authDomain: 'fireguardpro-ba880.firebaseapp.com',
    databaseURL: 'https://fireguardpro-ba880-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fireguardpro-ba880.appspot.com',
    measurementId: 'G-YLPT7H2LZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvY9lxmvA3mNPm3SsRbUuSdx67D7bv5rM',
    appId: '1:1047895517233:android:8d5890ce5603ce1cd90d10',
    messagingSenderId: '1047895517233',
    projectId: 'fireguardpro-ba880',
    databaseURL: 'https://fireguardpro-ba880-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fireguardpro-ba880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5kHNq0bSbbppP93TSEswORwvhmoyYcE',
    appId: '1:1047895517233:ios:cf84aaded7886b72d90d10',
    messagingSenderId: '1047895517233',
    projectId: 'fireguardpro-ba880',
    databaseURL: 'https://fireguardpro-ba880-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fireguardpro-ba880.appspot.com',
    iosBundleId: 'com.example.fireguardPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5kHNq0bSbbppP93TSEswORwvhmoyYcE',
    appId: '1:1047895517233:ios:cf84aaded7886b72d90d10',
    messagingSenderId: '1047895517233',
    projectId: 'fireguardpro-ba880',
    databaseURL: 'https://fireguardpro-ba880-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fireguardpro-ba880.appspot.com',
    iosBundleId: 'com.example.fireguardPro',
  );
}
